# Generated by Django 3.0.3 on 2020-02-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='menu_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=1000)),
                ('image_present', models.BooleanField()),
                ('large_portion_name', models.CharField(default='', max_length=30, null=True)),
                ('name', models.CharField(default='', max_length=100)),
                ('price_large', models.IntegerField()),
                ('price_small', models.FloatField()),
                ('short_name', models.CharField(default='', max_length=10)),
                ('small_portion_name', models.CharField(default='', max_length=10, null=True)),
            ],
        ),
    ]
