# Generated by Django 3.0.3 on 2020-02-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_item',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
